### ISSUE TITLE
Add an option to throw error on termination

### ISSUE THREAD

**Issue by matheo** [johnny-mh/rxjs-shell#16]
https://github.com/johnny-mh/rxjs-shell/blob/c76d6f30a58d73c7a72ca41783f830aa1e3c3ef5/src/exec.ts#L26

I'm looking for a way to know if a process was killed prematurely
and I think we could have an option here to report it as error before complete?

**Comment by johnny-mh** [comment]
Sorry for late. I'll check this issue tonight.

**Comment by johnny-mh** [comment]
@matheo Could you tell me a little bit about the situation?

It's reading like that

"Stream(RXJS) completed before process terminated. The stream must not completed before process termination."

**Comment by matheo** [comment]
Hi @johnny-mh sure thing!
I'm running a stream of actions and I do want to cancel the whole thing when I Ctrl+C in the middle of them.

Right now, it ends the current command in the stream
but the next continues (because concatMap continues or whatever)
so I want to be able to detect when a process is terminated, and stop everything.

I hope it's clear enough :)

**Comment by johnny-mh** [comment]
Okay please make sure I understand!

Bunch of shell scripts tide rxjs stream like below code.

```ts
exec('git clone https://https://github.com/johnny-mh/rxjs-shell').pipe(
  concatMap(() => exec('cp rxjs-shell/README.md ./test.md')),
  concatMap(() => exec('sed -n "3,7p" ./test.md ')),
  // ... blah blah ...
).subscribe()
```

While `cp` executing you pressed `Ctrl + C` to terminate whole process

But `sed` execute and you don't want. you want stop whole process after `git clone` right?

**Comment by matheo** [comment]
Exactly, I think it would be good to have a way to not reach the following commands and not reach the end :)

**Comment by johnny-mh** [comment]
In that case. you can use `listenTerminating` utility method to terminate whole process.

see https://github.com/johnny-mh/rxjs-shell#listenterminatingfn---any

```ts
// when your nodejs process terminated by SIGINT OR SIGBREAK. Terminate your whole nodejs process. 
listenTerminating(code => process.exit(code));  

exec('git clone https://https://github.com/johnny-mh/rxjs-shell').pipe(
  concatMap(() => exec('cp rxjs-shell/README.md ./test.md')),
  concatMap(() => exec('sed -n "3,7p" ./test.md ')),
  // ... blah blah ...
).subscribe()
```

`listenTerminating` just listen your root process's `Ctrl+C` event and execute callback.

**Comment by matheo** [comment]
OMG
I've missed that one!
thanks a lot for such great stuff ^.^
