### ISSUE TITLE
Error TS2688: Cannot find type definition file for 'mocha'

### ISSUE THREAD

**Issue by hong-duc** [johnny-mh/rxjs-shell#17]
Here is the full error
```
node_modules/rxjs-shell/dist/util.d.ts:2:23 - error TS2688: Cannot find type definition file for 'mocha'.

/// <reference types="mocha" />
```
Can you remove the above line ? I cannot install mocha because it will conflit with jest and throw a bunch of error when build. Thanks

**Comment by johnny-mh** [comment]
Hi @hong-duc 

I resolve this issue and make PR #18 please check this if you want.

I will merge the PR after three or four hours 😄

**Comment by hong-duc** [comment]
Soo fast thank you 😄

**Comment by johnny-mh** [comment]
@hong-duc v3.0.5 released!
