### ISSUE TITLE
Usage with a CLI command

### ISSUE THREAD

**Issue by matheo** [johnny-mh/rxjs-shell#9]
Hi @johnny-mh 
First, thanks for this great library!

I'm building some complicated npm scripts, and I have a simple question:

I've used `spawn` in some of them and it seems that I'm having memory leaks caused by orphan threads, so I wonder if `rxjs-shell` takes care of the canceled commands (via `Ctrl+C`) when its `spawn` or `exec` is running.

Thanks again!

**Comment by johnny-mh** [comment]
@matheo I've missed that feature. So i created 'Pull Request' to fix it. Please review that freely if you want. It will be publishing v1.0.4 at tomorrow. Thank you!

**Comment by matheo** [comment]
@johnny-mh WOW! awesome!
Thank you very much!!

I've found that windows have an issue triggering the event
so I've used this workaround in the meantime:
```
const sigInt = new Subject<void>();

if (process.platform === 'win32') {
  const rl = createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  rl.on('SIGINT', () => process.emit('SIGINT'));
}

process.on('SIGINT', () => sigInt.next());

export function takeUntilSigint<T>(): MonoTypeOperatorFunction<T> {
  return takeUntil<T>(sigInt);
}
```
just to cover the `Ctrl+C` :)

The behavior after the PR is to Complete the stream then?
Thanks again for such a fast answer!

**Comment by matheo** [comment]
BTW, my scripts worked pretty well with the current version of `rxjs-shell`,
I've found that some of my problems were caused by VSCode Extensions :)

**Comment by johnny-mh** [comment]
Operator that you posted does not need after v1.0.4.

I've tested stream cancellation on `Ctrl+C` pressed or execute `process.emit('SIGINT')`. 

and found some bugs like `exec` methods didn't completely killed because of sub process issue.

That's why I adding `tree-kill` package. Thank you!

**Comment by johnny-mh** [comment]
@matheo v1.0.4 published :)

**Comment by matheo** [comment]
Great stuff @johnny-mh 
Thank you very much!
